// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexosMedical.Api.Data;

namespace NexosMedical.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NexosMedical.Api.Data.Entities.CitaMedica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DoctorId");

                    b.Property<DateTime>("FechaCita");

                    b.Property<string>("Notas");

                    b.Property<int?>("PacienteId");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PacienteId");

                    b.ToTable("CitasMedicas");
                });

            modelBuilder.Entity("NexosMedical.Api.Data.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("HospitalDondeTrabaja")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("NumeroCredencial")
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("NexosMedical.Api.Data.Entities.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodigoPostal")
                        .HasMaxLength(10);

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("NumeroSeguroSocial")
                        .HasMaxLength(25);

                    b.Property<string>("TelefonoContacto")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("NexosMedical.Api.Data.Entities.CitaMedica", b =>
                {
                    b.HasOne("NexosMedical.Api.Data.Entities.Doctor", "Doctor")
                        .WithMany("CitasMedicas")
                        .HasForeignKey("DoctorId");

                    b.HasOne("NexosMedical.Api.Data.Entities.Paciente", "Paciente")
                        .WithMany("CitasMedicas")
                        .HasForeignKey("PacienteId");
                });
#pragma warning restore 612, 618
        }
    }
}
